name:     "PHP Decimal"
title:    "Arbitrary-precision decimal arithmetic for PHP 7"
tagline:  "Arbitrary-precision decimal arithmetic for PHP 7"
github:   "php-decimal"
travis:   "php-decimal/ext-decimal"
